FROM ubuntu:24.04

WORKDIR /app

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
        python3 python3-pip \
        git curl lsof cron \
        ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip3 install --break-system-packages -r requirements.txt

# Copia o repositório inteiro
COPY . .

# Garante permissões de execução
RUN chmod +x *.sh

# Cria estrutura mínima necessária
RUN mkdir -p logs bots

CMD ["bash"]
